# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Site settings
permalink: /:title.html
exclude:
  - Makefile
  - README.md
  - EXTRAS.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - CNAME
sass:
  style: compressed

# Site info
url: "http://ricostacruz.com/vim-hyperstyle"
title: vim-yperstyle

# Google analytics
analytics:
  hostname: "ricostacruz.com"
  id: "UA-20473929-1"

# Default variables
defaults:
  - scope:
      path: ""
    values:
      layout: "article"
      tags: []
      author: John Smith
